electron/cli/index.js
electron/index.js

Added this commit on the shell repo, forgot to add it here.

Fix electron

---

src/Accounts/Accounts.js
src/Accounts/CreateAccount/CreateAccountStep1/CreateAccountStep1.js
src/Accounts/CreateAccount/CreateAccountStep2/CreateAccountStep2.js
src/Accounts/CreateAccount/CreateAccountStep3/CreateAccountStep3.js
src/Accounts/CreateAccount/CreateAccountStep4/CreateAccountStep4.js
src/Accounts/CreateAccount/CreateAccountStep5/CreateAccountStep5.js
src/App/ProtectedRoute/ProtectedRoute.js
src/Loading/Loading.js
src/Send/Signer/Signer.js
src/Tokens/NewToken/NewToken.js
src/Tokens/NewToken/NewTokenItem/NewTokenItem.js
src/Tokens/Tokens.js
src/Tokens/TokensList/TokensList.js
src/stores/tokensStore.js

Closes #6.
Before I had one localStorage list of tokens per chain.
Now it's one list per chain per account. Which makes more sense.

Tokens per chain per account

---

electron/index.js
electron/operations/isParityRunning.js
electron/operations/runParity.js
package.json
yarn.lock

Accidentally merged #23 into am-tokens-part2 branch instead of master. Resubmitting pr.

[Fix] Check if parity is running

---

package.json
src/Health/Health.js
src/Loading/Loading.js
src/stores/healthStore.js
src/stores/index.js
src/stores/parityStore.js
yarn.lock

Closes #3.
The syncing icon has these states, and can have 3 colors (red, yellow, green) depending on which state we're in:
```javascript
export const STATUS = {
CANTCONNECT: 'CANTCONNECT', // Can't connect to Parity's api
CLOCKNOTSYNC: 'CLOCKNOTSYNC', // Local clock is not sync
DOWNLOADING: 'DOWNLOADING', // Currently downloading Parity
GOOD: 'GOOD', // Everything's fine
NOINTERNET: 'NOINTERNET', // No network connection
OTHER: 'OTHER', // Unknown state, might have a payload
RUNNING: 'RUNNING', // Currently try to launch Parity
SYNCING: 'SYNCING' // Obvious
};
```
A demo:
(Note the speed of the light sync 8))
@brianflanagan: in some of those states above, we could show an overlay, a "how to fix" message, or disable some buttons.

Sync state

---

package.json
src/Send/Send.js
src/Tokens/TokensList/BalanceLayout/BalanceLayout.js
src/Tokens/TokensList/EthBalance/EthBalance.js
src/Tokens/TokensList/TokenBalance/TokenBalance.js
yarn.lock

Before I was putting random values.

Use real values for tokens

---

packages/light-react/src/App/App.js
packages/light-react/src/Overlay/Overlay.js
packages/light-react/src/assets/sass/components/_alert-screen.scss
packages/light-react/src/assets/sass/layouts/_wrapper.scss
packages/light-ui/src/AccountHeader/AccountHeader.js

The "Syncing..." overlay will only show if we're syncing for at least 3s.

Prevent Overlay from flashing

---

packages/light-react/src/Overlay/Overlay.js
packages/light-react/src/Send/Sent/Sent.js
packages/light-react/src/assets/sass/components/_alert-screen.scss
packages/light-react/src/assets/sass/layouts/_wrapper.scss

Change etherscan link in Sent (fix #50)

---

packages/light-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
packages/light-react/src/stores/createAccountStore.js

Remove password hint (fix #61)

---

packages/light-react/src/App/App.js
packages/light-react/src/Health/Health.js
packages/light-react/src/Onboarding/Onboarding.js
packages/light-react/src/Overlay/Overlay.js
packages/light-react/src/Send/TxForm/TxForm.js
packages/light-react/src/Settings/NewTokenItem/NewTokenItem.js
packages/light-react/src/Settings/Settings.js
packages/light-react/src/stores/healthStore.js
packages/light-react/src/stores/sendStore.js
packages/light-ui/src/TokenCard/TokenCard.js

@Tbaut once merged, when you pull and run, make sure to run `localStorage.clear()` inside electron first.

Fix bug gavcoin not sent

---

packages/light-react/src/Accounts/AccountsList/AccountsList.js
packages/light-react/src/Accounts/CreateAccount/CreateAccount.js
packages/light-react/src/App/App.js
packages/light-react/src/Onboarding/Onboarding.js
packages/light-react/src/Tokens/Tokens.js
packages/light-react/src/assets/sass/shared/_form.scss
packages/light-react/src/stores/createAccountStore.js
packages/light-react/src/stores/onboardingStore.js

Add a placeholder for the Terms of Use, waiting for content from Fraser.
To test: `localStorage.clear()` and refresh the page.

Make onboarding work

---

packages/light-react/package.json
packages/light-react/src/Onboarding/Onboarding.js
packages/light-react/src/Send/Signer/Signer.js
packages/light-react/src/Send/TxForm/TxForm.js
packages/light-react/src/assets/sass/shared/_button.scss
packages/light-react/src/stores/sendStore.js
packages/light-ui/src/FormField/FormField.js
yarn.lock

Overall make forms more usable.
Also fixes #68, fixes #73, fixes #74.

Form validations and error message

---

packages/fether-electron/package.json
packages/fether-electron/src/main/cli/index.js
packages/fether-electron/src/main/index.js
packages/fether-react/public/index.html
yarn.lock

Remove `--ui-dev` flag. Add CSP to remove warning.

Small tweaks on Electron

---

packages/fether-electron/package.json
packages/fether-electron/src/main/index.js
packages/fether-react/src/App/App.js
packages/fether-react/src/assets/sass/layouts/_wrapper.scss
packages/fether-react/src/assets/sass/shared/_basics.scss
yarn.lock

Add menubar

---

README.md
packages/fether-electron/electron-builder.json
packages/fether-electron/src/main/index.js
packages/fether-react/public/index.html
packages/fether-ui/README.md

Fix binaries

---

packages/fether-react/src/Settings/Settings.js

- fix https://github.com/parity-js/fether/issues/103

Remove "Edit"

---

packages/fether-react/package.json
packages/fether-react/src/Send/TxForm/TxForm.js
packages/fether-react/src/assets/sass/modules/_reset.scss
packages/fether-react/src/stores/sendStore.spec.js
packages/fether-react/src/utils/estimateGas.js
packages/fether-react/src/utils/estimateGas.spec.js
packages/fether-react/src/utils/testHelpers/mock.js
packages/fether-react/src/utils/withBalance.js
packages/fether-ui/src/Form/Field/Field.js
packages/fether-ui/src/Form/Slider/Slider.js

One part of the estimate gas was not implemented yet: making sure that when sending tokens, the user had enough eth balance.
Added in this PR.

Estimate Gas for tokens too

---

packages/fether-react/src/Send/TxForm/TxForm.js
packages/fether-react/src/assets/sass/shared/_form.scss

- set value to 0.00
- make it more transparent

Patch placeholder to look like a placeholder

---

packages/fether-react/src/Send/TxForm/TxForm.js
packages/fether-ui/src/Form/Field/Field.js

Fix : https://github.com/paritytech/fether/issues/133

Clickable label + Slow instead of Cheap

---

packages/fether-electron/src/main/index.js
packages/fether-electron/src/main/messages/index.js
packages/fether-react/package.json
packages/fether-react/src/App/App.js
packages/fether-react/src/assets/sass/layouts/_wrapper.scss
packages/fether-react/src/assets/sass/shared/_basics.scss
yarn.lock

So that it fits the content size.

Resize electron window

---

packages/fether-react/package.json
packages/light-hoc/package.json
yarn.lock

Use https://github.com/parity-js/light.js/pull/7

Update light.js dependency (now without precompiled lib/)

---

packages/fether-react/package.json
packages/fether-react/src/Health/Health.js
packages/fether-react/src/Overlay/Overlay.js
packages/fether-react/src/assets/sass/components/_alert-screen.scss
packages/fether-react/src/stores/healthStore.js
packages/light-hoc/package.json
yarn.lock

Uses https://github.com/parity-js/light.js/pull/8
Need to update dependency as soon as the other PR is merged

Remove nodeHealth$, use peerCount$

---

packages/parity-electron/src/fetchParity.ts

Download Parity as `parity.part` or `parity.exe.part` ; rename it to `parity` or `parity.exe` once the download is finished and the checksums are verified. Fixes https://github.com/paritytech/fether/issues/173

Download parity as parity[.exe].part and then rename

---

.travis.yml
package.json
packages/fether-electron/src/main/index.js
packages/fether-react/scripts/updateTokens.js
packages/fether-react/src/stores/createAccountStore.js
packages/fether-react/src/stores/healthStore.js
packages/fether-react/src/stores/onboardingStore.js
packages/fether-react/src/stores/parityStore.js
packages/fether-react/src/stores/sendStore.js
packages/fether-react/src/stores/tokensStore.js
packages/fether-ui/src/AddressShort/AddressShort.js
packages/parity-electron/src/fetchParity.ts
packages/parity-electron/src/isParityRunning.ts
packages/parity-electron/src/runParity.ts
scripts/lint-files.sh
yarn.lock

When committing, [husky](https://github.com/typicode/husky) will lint the staged files and fix what can be fixed. If some things cannot be fixed, the commit is aborted.

Set up semistandard + prettier & lint pre-commit hook

---

packages/fether-react/src/stores/tokensStore.js

Having "Send Ethereum" in the title felt wrong :)

Name the currency Ether

---

packages/fether-react/package.json
packages/fether-react/scripts/updateTokens.js
packages/fether-react/src/utils/estimateGas.js
packages/fether-react/src/utils/estimateGas.spec.js
packages/fether-react/src/utils/withBalance.js
yarn.lock

Instead of the unmaintained `@parity/shared`.

Use @parity/contracts

---

README.md

Mainly for @gabreal to test sync with gitlab.

Update link to light.js

---

packages/fether-react/package.json
packages/fether-react/src/Send/Sent/Sent.js
packages/fether-react/src/Send/TxForm/TxForm.js
packages/fether-react/src/Whitelist/Whitelist.js
packages/fether-react/src/stores/healthStore.js
packages/fether-react/src/stores/sendStore.js
packages/fether-react/src/stores/sendStore.spec.js
packages/fether-react/src/utils/estimateGas.js
packages/fether-react/src/utils/testHelpers/mock.js
packages/fether-react/src/utils/withBalance.js
packages/fether-react/src/utils/withTokens.js
yarn.lock

Use new version of @parity/light.js

---

packages/fether-react/src/Accounts/AccountsList/AccountsList.js

Closes https://github.com/paritytech/fether/issues/213
introduced in https://github.com/paritytech/fether/pull/211

Fix markup (fix gap between accounts in AccountsList)

---

packages/fether-react/package.json
packages/fether-react/src/Send/Sent/Sent.js
packages/fether-react/src/stores/sendStore.js
packages/fether-react/src/stores/sendStore.spec.js
packages/fether-react/src/utils/estimateGas.js
packages/fether-react/src/utils/testHelpers/mock.js
yarn.lock

- Fix #206, fix #208, fix #201.
- Fix bug when refreshing page on the Sent tx page
- Fix bug show node errors on Signer page
- Fix bug same token balance

Fix the symbol bug

---

.gitlab-ci.yml

This job was failing https://gitlab.parity.io/parity/fether/-/jobs/107422

Don't install node on CI

---

packages/fether-react/package.json
yarn.lock

Fix bug confirmations not working with latest light.js

---

README.md

- I need help for the mac instructions @amaurymartiny :)

Update readme with clearer install instructions

---

README.md

Removing the "fast" for now

---

lerna.json
package.json
packages/fether-electron/package.json
packages/fether-react/package.json
packages/fether-ui/package.json

Bump to version 0.1.1

---

packages/fether-react/src/Whitelist/Whitelist.js

Select default array from imported list of tokens

---

packages/fether-react/src/Whitelist/Whitelist.js

#304 did not fix the problem, it appears that the squashing is not working as expected.

Fix non working squashing

---

packages/fether-react/src/Send/Signer/Signer.js
packages/fether-react/src/assets/sass/shared/_form.scss

Switch order from "to" and "amount" fields on Signer screen

---

packages/fether-react/src/Send/TxForm/TxDetails/TxDetails.js
packages/fether-react/src/Send/TxForm/TxForm.js

- Closes #334
- Show the "Details" toggle any time
- Show ~~"Transaction incomplete"~~ edit: `Missing input fields...` in case not all fields are completed and we have a valid transaction.
- Tiny wording changes
It looks like this:

"Transaction Details" viewable any time

---

lerna.json
package.json
packages/fether-electron/package.json
packages/fether-react/package.json
packages/fether-ui/package.json

My linter removed empty lines at the end of files. Let me know if that's a problem.

Bump version to 0.2.0

---

packages/fether-react/src/stores/createAccountStore.js

- closes #350
- tested successfully with a recovery phrase generated by Parity Signer

Accept 11 words legacy recovery phrases for Parity Signer compatibility

---

packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js

Fix Warning about unique "key" prop

---

packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js
packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js
packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js
packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js
packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js
packages/fether-react/src/BackupAccount/BackupAccount.js
packages/fether-react/src/Send/ScanSignedTx/ScanSignedTx.js
packages/fether-react/src/Send/TxQrCode/TxQrCode.js
packages/fether-react/src/Send/Unlock/Unlock.js
packages/fether-react/src/assets/sass/shared/_button.scss

Refer to https://github.com/paritytech/fether/pull/364#pullrequestreview-193395290

Change Cancel to Back button. Password field autofocus on Unlock component

---

packages/fether-react/src/utils/withHealth.js

- closes: https://github.com/paritytech/fether/issues/369
- The `syncStatus$` was emitting several `isSync: false` more frequently than 2s because the blocks (also part of `syncStatus$`) were changing. This prevented `rpc$` to be emitting and the UI to be updated.
- `audit` allows to delay the emission of an event of 2s when not synced. The down side of this solution is that when syncing we only get the sync rate every 2s.
- all and all what changed is L115, my linter makes it look bigger than it is.

Fix sync rate not showing

---

packages/fether-react/package.json
packages/fether-react/src/App/App.js
packages/fether-react/src/RequireHealthOverlay/HealthModal/HealthModal.js
packages/fether-react/src/Send/Sent/Sent.js
packages/fether-react/src/Tokens/TokensList/TokensList.js
packages/fether-react/src/assets/sass/components/_alert-screen.scss
packages/fether-ui/src/Modal/Modal.js

closes #313 
On startup, if there is a GitHub release with a version more recent than the current version, display a modal with a link to the GitHub release.

Check for new Fether release & prompt user on startup

---

packages/fether-react/src/App/App.js

index.js:1446 Warning: App has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean componentWillUnmount()?

fix: Fix warning since lifecycle method should be componentWillUnmount

---

README.md

- Any content that was removed in this PR was copied to https://wiki.parity.io/Fether-FAQ

Move unessential content to the wiki

---

packages/fether-react/src/Scanner/Scanner.js
packages/fether-react/src/assets/sass/shared/_basics.scss
packages/fether-ui/src/ExternalLink/ExternalLink.js
packages/fether-ui/src/ExternalLink/index.js
packages/fether-ui/src/index.js

Note that `https://wiki.parity.io/Fether-FAQ` has been added to the list of `TRUSTED_URLS` in branch luke-124-security https://github.com/paritytech/fether/pull/451

fix: Relates to #466. Update Webcam error messages to refer to Fether FAQ

---

scripts/fetch-latest-parity.js

closes https://github.com/paritytech/fether/issues/480

Use path join to build on Windows

---

scripts/fetch-latest-parity.js

continuing https://github.com/paritytech/fether/pull/487

Use path.join in fetch-latest-parity.js

---

packages/fether-electron/src/main/app/methods/setupRequestListeners.js
packages/fether-react/public/index.html

#516 Set CSP in Meta tag

---

packages/fether-electron/package.json
yarn.lock

fixes #521 
Use `yarn package` to test, works for me on macos

fix: Update to electron 5 to fix context isolation

---

packages/fether-react/src/App/App.js
packages/fether-react/src/DeleteAccount/DeleteAccount.js
packages/fether-react/src/DeleteAccount/index.js
packages/fether-react/src/Tokens/Tokens.js
packages/fether-react/src/i18n/locales/de.json
packages/fether-react/src/i18n/locales/en.json

fixes #448 
Unfortunately I didn't add German translations. I can deepl them, but not sure it's the best

feat: Delete account

---

packages/fether-electron/src/main/app/methods/setupRequestListeners.js

feat: Add electron security to disallow permission

---

packages/fether-electron/src/main/app/menu/template/index.js
packages/fether-electron/src/main/app/options/config/index.js

closes: https://github.com/paritytech/fether/issues/534

Feat: only show dev tools in dev environment

---

yarn.lock

Update packages (some security patches).
Tried: view balance, send tx.

chore: Run yarn upgrade

---

packages/fether-electron/src/main/app/ipcChannel/index.js
packages/fether-react/src/utils/PostMessageProvider.js

fix: Only emit correctly-formed JSONRPC message

---

README.md

- closes https://github.com/paritytech/fether/issues/551
Thanks to @kirushik who helped me to document this attack.

Add Appimage security warning

---

packages/fether-react/src/utils/PostMessageProvider.js

close https://github.com/paritytech/fether/issues/560#issuecomment-545858683

Fix unhandled transport errors

---

packages/fether-react/src/utils/PostMessageProvider.js

close https://github.com/paritytech/fether/issues/566

Fix PostMessageProvider unsubscribe

---

packages/fether-electron/electron-builder.json

Copy paste of https://github.com/ipfs-shipyard/ipfs-desktop/pull/1069
Trying to fix https://gitlab.parity.io/parity/fether/-/jobs/260245

 chore: do not upload to snap store

---

packages/fether-electron/electron-builder.json

Forgot something in https://github.com/paritytech/fether/pull/570

chore: Don't upload to snap store, part 2

---

package.json
packages/fether-react/package.json
yarn.lock

Upgrade serialize-javascript to version 2.1.1 or later.
Ran: `yarn add react-scripts` in fether-react

chore: Update package (security patch)

---

lerna.json
package.json
packages/fether-electron/package.json
packages/fether-react/package.json
packages/fether-ui/package.json

this should help for the latest issues to pass the hardfork.
- #583
- #582
Synced Mainnet without problem.

Upgrade parity to latest stable and bump to 0.4.3

---

packages/fether-electron/package.json
scripts/fetch-latest-parity.js

Tested and working fine. I'd do a (last?) release after.

chore: Use Parity 2.7.2
