paritytech/fether

electron/index.js, electron/operations/isParityRunning.js, electron/operations/runParity.js, package.json, yarn.lock
Instead of using `ps-node` and doing a `ps aucx | grep parity` to find out if an instance of parity is already running, we now do something simpler. We just ping:
- `127.0.0.1:8545`
- `127.0.0.1:8546`
- and whatever --ws-port and --ws-interface the user inputs.
If one of them is responding, then we assume there's a parity instance running. This should cover most of the use cases.
The reason why we drop `ps-node` is that there might be another command containing parity in the name (e.g. parity-ui, parity*?) which would create false positives hard to debug.
Also, if there indeed *is* another parity running (on a custom port), then electron will still launch its own parity, but there would be a recognizable error (`lock file in use`, or `...is already in use`); we catch those errors, and …
=> Check if parity is running

packages/fether-react/src/assets/sass/components/_account.scss, packages/fether-ui/src/AddressShort/AddressShort.js
- Make full address a little bigger on the account screen
- Show the first 4 digits of the address on general screen (including "0x", so 6 digits)
=> Address readability

packages/fether-react/package.json, packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/stores/sendStore.js, packages/fether-react/src/stores/sendStore.spec.js
Now we **require** an estimateGas before sending a transaction. Slightly slower UX, but will avoid the 115 bug.
=> Fix sending more than max balance

package.json
Before: we were building `@parity/electron` parallely to running `yarn start` in fether-electron.
Now: We build `@parity/electron` first, then run `yarn start` in fether-electron
Note: `@parity/electron` will get out of this repo one day, so there will be no need to build it here.
=> Fix bug yarn start

packages/fether-react/src/stores/sendStore.spec.js, packages/fether-react/src/utils/estimateGas.js, packages/fether-react/src/utils/estimateGas.spec.js, packages/fether-react/src/utils/testHelpers/mock.js, packages/fether-react/src/utils/withBalance.js
`makeContract` is an object whose values are observables, this object shouldn't have $ in its name.
Fixes #171.
=> Change makeContract$ to makeContract

packages/fether-react/src/App/App.js, packages/fether-react/src/Health/Health.js, packages/fether-react/src/Overlay/Overlay.js, packages/fether-react/src/utils/withHealth.js
- Fix 'Downloading: NaN%'
- Start with 'Syncing...' if we don't know if we're synced (makes more sense to go from 'Syncing...' to 'Synced' if we were initially synced than it makes sense to go from 'Synced' to 'Syncing...' if we weren't synced initially)
- Renamed "STATUS.RUNNING" to "STATUS.LAUNCHING" to avoid ambiguity
- Fix inconsistencies in the health messages; before this PR we would have "Cannot connect to Parity" pop up out of nowhere for example. There is no way to distinguish "Cannot connect to Parity" to "Connecting to Parity" (getting a token from the signer) currently; plus isApiConnected$ is updated every second only, so this makes for a lot of inconsistencies in the health messages being shown. Now we make "Launching..." the default beginning value instead of "Cannot …
=> Improvements to health status

packages/fether-electron/package.json
The major bug has been fixed and Parity Ethereum released.
=> Switch back to Parity Ethereum beta

packages/fether-react/src/Send/Signer/Signer.js, packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/Whitelist/Whitelist.js
- fix #233
- Because mobile view works the same way (only with back arrows) I've change all the ones I found.
=> Use arrow instead of close icons

packages/fether-react/package.json, packages/fether-react/src/RequireHealthOverlay/RequireHealthOverlay.js, packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/utils/estimateGas.js, packages/fether-react/src/utils/withHealth.js, yarn.lock
- Do not add any "gas buffer" (currently 25% for any transaction) when we realize that the transaction is between 2 accounts, and therefore costs invariably 21'000 Wei
- Pass the gas information to the `parity_postTransaction` RPC to prevent any error from the node. The node knows nothing about the transaction and does not estimate gas (too costly) so it defaults to an amount of gas that is much greater than 21000.
- Should fix https://github.com/paritytech/fether/issues/265 and #250
=> Add gas estimation to the `postTransaction` RPC

README.md
When running `yarn start` the Electron screen may just remain white indefinitely even though it said it compiled and has been syncing blocks for a while. Instead of having to resort to using `yarn electron` (which doesn't have this issue, but doesn't provide benefits such as live reload and more detailed debugging), the solution appears to be as simple as going to 'View > Reload' in the Electron menu (or entering shortcut CMD + R on macOS)
=> docs: Add troubleshooting tip suggesting to reload when stuck on white screen

packages/fether-react/src/Accounts/CreateAccount/AccountCopyPhrase/AccountCopyPhrase.js, packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js, packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js, packages/fether-react/src/Accounts/CreateAccount/AccountRewritePhrase/AccountRewritePhrase.js, packages/fether-react/src/BackupAccount/BackupAccount.js, packages/fether-ui/src/Form/Field/Field.js
@yjkimjunior Can we try and use the `onSubmit` prop on a `<form>`? I proposed here just one example on AccountName, but I think the same thing could work everywhere. I.e. don't add onSubmit on fields, but on the wrapping form. We could delete all usage of event.keycode too.
To be merged into #323
=> Merge into yj-focus-formfield - Don't use keycodes

packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/assets/sass/shared/_form.scss
* Switches to font size that fits a value as small as 1 Wei on the screen when more than 9 digits entered
* Switches back to default font size when amount of digits entered is 9 or less again
* Caters for when user unchecks the Max Value button
=> feat: Fixes #308. Change amount font size on Send page to fit in input field

packages/fether-react/src/Accounts/CreateAccount/AccountImportOptions/AccountImportOptions.js, packages/fether-ui/src/AddressShort/AddressShort.js, packages/fether-ui/src/index.js, packages/fether-ui/src/utils/addressShort.js, packages/fether-ui/src/utils/index.js
* Prevents user from importing account and show the message in the screenshot below when they go to "Import account" and select a JSON Backup Keyfile whose address is already associated with an account that is already in the account list
* Prevents user from importing account and show the message in the screenshot below when they go to "Import account" and enter a Seed Phrase that corresponds to an address that is associated with an account that is already in the account list
=> fix: Relates to #138. Prevents user from importing account that is already in account list

packages/fether-react/src/Send/Sent/Sent.js, packages/fether-react/src/stores/sendStore.js
Might fix https://github.com/paritytech/fether/issues/379
Previously, we would resolve the promise and then set `this.txStatus`. However, resolving the promise actually redirects to `Sent` which expects `txStatus` to already be defined
=> fix: Fix txStatus race condition in sendStore

packages/fether-electron/package.json, yarn.lock
* Fixes the error by adding ansi-styles to dependencies
* Additional dependencies updated (unrelated to the bug)
* Checked that it works after running `rm yarn.lock; rm -rf node_modules/`
* Checked that it works with both `yarn; yarn electron` and `yarn; yarn start`
* Checked that .dmg works on macOS and that .deb works on Ubuntu Gnome
=> fix: Fixes #401. Add ansi-styles to fix bug. Update other dependencies

packages/fether-electron/src/main/app/messages/index.js
Note that in addition to resolving the bug, this PR introduces an animation (supported only on macOS) when the window resizes
=> fix: Fixes #408 window resize by converting args[0] height to integer for setContentSize

packages/fether-react/src/App/App.js, packages/fether-react/src/stores/parityStore.js
Fix race condition (fixes https://github.com/paritytech/fether/issues/333)
Replaces closes https://github.com/paritytech/fether/pull/412
Can reproduce/test by disabling getting the token from localStorage in `parityStore` and adding a few seconds of delay after calling `this.setToken` in `requestNewToken` in `parityStore` (crashes on master but not on this branch).
=> Fix light.setApi race condition

packages/fether-react/src/App/App.js, packages/fether-react/src/Health/Health.js, packages/fether-react/src/RequireHealthOverlay/HealthModal/HealthModal.js, packages/fether-react/src/utils/withHealth.js
To test:
- Fresh install `rm -rf ~/Library{Application Support/{io.parity.ethereum | Electron | fether}`
- yarn electron
On master, #416 introduced a bug where, on fresh launch, a blank screen was shown (because of [these lines](https://github.com/paritytech/fether/blob/ebb39a444c69df5bc908a20bc42fc78768a2ebb5/packages/fether-react/src/App/App.js#L56-L58)).
This PR basically just replaces this `null` with a `RequireHealthOverlay`.
Moreover, `<Health>` and `<HealthModal>` (both can be rendered before api is defined) use light.js's `chainName$` when syncing/synced, but we only allow calling this method when the api is connected.
=> fix: Fresh sync shows blank screen

packages/fether-electron/src/main/app/messages/index.js
* When you run `yarn; TASKBAR=false yarn start` and then choose from Fether menu  "Window > Close Window" and then re-open it by clicking the dock icon on macOS it gives error Cannot getContentSize of undefined, this resolves the issue
=> fix: Fixes cannot getContent of undefined bug when run TASKBAR=false and Close Window then re-open it

packages/fether-electron/src/main/app/options/config/index.js
I think this actually restores it the way is once was
Screenshot on Linux Mint
=> fix: Fixes #421. Linux tray and dock icon not pixelated and Fether branding

README.md
* Add section with commands that may be copy/pasted to install required dependencies
* Updates the "Usage of taskbar mode" section
* Adds a "Production" section with subsections including "Build binaries for production" and "Debugging in production"
* Complements changes that have been made in PR https://github.com/paritytech/fether/pull/440
=> docs: Update Readme with dependencies, guide for taskbar usage and building and debugging production

packages/fether-electron/electron-webpack.json, packages/fether-electron/package.json, packages/fether-electron/src/main/app/options/config/index.js, packages/fether-electron/src/main/app/options/config/preload.js, packages/fether-react/package.json, packages/fether-react/src/stores/parityStore.js, packages/fether-react/src/utils/withHealth.js, yarn.lock
@ltfschoen a patch to your PR that uses preload scripts. I played around a little bit, I think unfortunately we can't use `contextIsolation=true` if we wish to use ipcRenderers.
=> Use preload script as buffer between main and renderer processes

packages/fether-react/src/assets/sass/components/_account.scss
closes #469
I've reduced the size 230->210px so that the hover on account copy looks good:
instead of
=> Center account header 

packages/fether-electron/src/main/app/menu/template/index.js
In the development environment only, when running Fether with `yarn start`, we have a known issue where a blank screen appears and we have to reload the window. On macOS and some Linux OS this is not an issue when the taskbar menu is available. However on Windows, there is no taskbar menu, so there user cannot choose "Reload" from the menu, since the menu that's shown upon right-click in the Fether window is only available in development after reloading the window.
As discussed with @Tbaut, propose to add "Reload" as an item to the menu that's show when you click the taskbar icon, so it will now show:
**development**
Show/Hide Fether
Reload
Quit
**production**
Show/Hide Fether
Quit
=> feat: Add Reload to taskbar menu in development only

scripts/fetch-latest-parity.js
Thanks to @fevo1971 for finding this!
https://gitlab.parity.io/parity/fether/-/jobs/132028
the permission of the downloaded binary was:
```
--wxrw--wt  1 administrator  staff  46128528 Mar 21 18:13 parity
```
We need to use octals to make it work cross-platform: https://nodejs.org/api/fs.html#fs_fs_chmod_path_mode_callback
=> fix: correctly set permissions on downloaded binary

packages/fether-react/src/utils/transaction.js
Transactions made using a Parity Signer accounts had a very low gas price. We usually deal with price in Gwei (also in the sendstore) until we send the tx. This conversion step was forgotten for Signer accounts.
closes https://github.com/paritytech/fether/issues/456
=> Convert the gasPrice to Gwei for Parity Signer transactions

packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/Tokens/TokensList/TokenBalance/TokenBalance.js, packages/fether-react/src/Tokens/TokensList/TokensList.js, packages/fether-react/src/index.js, packages/fether-react/src/utils/withAccount.js, packages/fether-react/src/utils/withBalance.js
Only the TxForm component needs the transaction count, so we don't make additional RPC calls on other screens.
fixes #420. It makes the overall transitions between screens quicker.
=> refactor: Don't call transactionCountOf$ until needed

packages/fether-react/src/assets/sass/components/_header-nav.scss, packages/fether-react/src/assets/sass/components/_token.scss
Some test tokens (kovan with the new token list) have very long names and "broke" the UI
It would now look like this:
=> Make sure long token names don't break the UI

packages/fether-react/src/assets/tokens/foundation.json, packages/fether-react/src/assets/tokens/goerli.json, packages/fether-react/src/assets/tokens/kovan.json, packages/fether-react/src/assets/tokens/ropsten.json, packages/fether-ui/src/TokenCard/TokenCard.js, scripts/updateTokens/update-tokens-utils.ts, scripts/updateTokens/update-tokens.ts
Because the security PR (https://github.com/paritytech/fether/pull/451) will prevent Fether from fetching random urls, we need to have one source for ERC-20 icons. I chose https://github.com/atomiclabs/cryptocurrency-icons/ github repo.
- Sadly ThibCoin and GavCoin have no face anymore, but most crypto have.
Here is an example with a mainnet random account:
```
localStorage.setItem("localforage/__paritylight::paritySignerAccounts", '[{"address":"0x564286362092D8e7936f0549571a803B203aAceD","name":"Random","chainId":1}]');
```
=> Use atomiclabs/cryptocurrency-icons/ set of icons

packages/fether-react/craco.config.js, packages/fether-react/package.json, yarn.lock
Update craco dependency and remove a workaround we had to use to fix `craco test` not taking `--react-scripts` into account (bug was fixed in the latest version of craco, https://github.com/sharegate/craco/issues/2)
=> refactor: Update craco and remove --react-scripts workaround

.gitlab-ci.yml, package.json, scripts/fetch-latest-parity.js
On gitlab we build the Windows binary on Linux: we need to fetch the windows parity-ethereum from linux.
`yarn fetch-parity --win` or `--mac` or `--linux`
=> chore: Allow fetching cross-platform parity-ethereum

packages/fether-react/package.json, packages/fether-react/src/Send/SignedTxSummary/SignedTxSummary.js, packages/fether-react/src/Send/TxForm/TxForm.js, packages/fether-react/src/Send/Unlock/Unlock.js, yarn.lock
fixes #537 
Repro:
- send tx
- on confirm screen, be idle for 1min
Expected: should go back to TxForm screen.
Note: Added on password unlock and Parity signer confirm screens.
=> feat: Add timeout on confirmation screens

packages/fether-react/package.json, yarn.lock
Gabriel just updated the CI machine to node 12, but then some packages break: https://gitlab.parity.io/parity/fether/-/jobs/221429
I suspect it's node-sass (see https://github.com/sass/node-sass/issues/2632), so trying this.
=> chore: Update node-sass to fix builds

packages/fether-electron/src/main/app/utils/isTrustedUrlPattern.spec.js, packages/fether-react/src/assets/tokens/foundation.json, packages/fether-react/src/assets/tokens/kovan.json, packages/fether-react/src/assets/tokens/ropsten.json, scripts/updateTokens/update-tokens-utils.ts
- closes : https://github.com/paritytech/fether/issues/535
- Using the commit corresponding to v0.16.1 https://github.com/atomiclabs/cryptocurrency-icons/releases/tag/v0.16.1
Tested by adding some new tokens to accounts such as MKR or DAI on Kovan and seeing that the call has the commit number + the icon shows up properly.
=> fix: get icons from a specific commit instead of master

packages/fether-electron/src/main/app/options/config/index.js, packages/fether-electron/static/preload.js
closes #548 
The issue describes filtering permissions in the `remote` module (point 16 in https://electronjs.org/docs/tutorial/security#16-filter-the-remote-module).
Instead, I did the more drastic point 15: remove altogether the `remote` module.
I would appreciate `yarn start` and `yarn electron` testing, they pass on my computer.
=> fix: Disable Electron remote module

packages/fether-react/src/Accounts/CreateAccount/AccountPassword/AccountPassword.js, packages/fether-react/src/i18n/locales/de.json, packages/fether-react/src/i18n/locales/en.json
- closes https://github.com/paritytech/fether/issues/549
Only allow at least 8 character long password with at least 1 number.
Look like this:
=> Add password criteria

.gitlab-ci.yml
Install node 12 on the docker image that builds windows binaries
Attempt to fix https://gitlab.parity.io/parity/fether/-/jobs/260945
Temporary measure until https://github.com/electron-userland/electron-builder/issues/4377 gets merged
=> fix: CI install node12 for windows

packages/fether-react/src/Accounts/CreateAccount/AccountName/AccountName.js, packages/fether-react/src/i18n/locales/de.json, packages/fether-react/src/i18n/locales/en.json
A simple fix #505. Disables the next button when an account with that name already exists.
=> fix duplicate account names 

packages/fether-electron/package.json
This is an insubstantial PR to trigger the CI and get [parity-ethereum v2.5.10](https://github.com/paritytech/parity-ethereum/releases) with Istanbul (coming in ~1 week). We can then release 0.4.1.
=> Force at least the Istanbul release
